### ISSUE TITLE
ORCHID - don't find Parameter.CreateSharedParameter node

### ISSUE THREAD

**Issue by judufr** [aussieBIMguru/Dynamo_Scripts#2]
Hello,
In first, thank you for your tuto and time for it.
But i have a problem with your learning for create a sharedparameters file by dynamo.
Like in the title, my package orchid is without this key node of the script.
And when i change the node by the "create"node" from orchid 230.0.3 (as the same with the 200), the script create an invalid file because (if i understand) the script write one column like this : 
![image](https://user-images.githubusercontent.com/69672440/90259779-e0484400-de4a-11ea-9422-fc740a243ba0.png)
[My_SP_List_Test - Copie.txt](https://github.com/aussieBIMguru/Dynamo_Scripts/files/5075099/My_SP_List_Test.-.Copie.txt)

"	HIDEWHENNOVALUE" don't exist in a valid file.

Do you have the same problem or one solution?

Thank you in advance.
Best regards.

Dynamo version-2.3.0.7661
Revit Version 2020.2
Orchid-230.03.7501
Thanks In advance,

**Comment by aussieBIMguru** [comment]
I don't think the hidewhennovalue is an issue - files have this typically.I'm able to open your parameter file with no problems in Revit 2020, it just has no groups or parameters set up.

The most common reasons for the script not working typically relate to people writing the parameter groups incorrectly (case or name matching). I would double check these in your excel inputs.

Orchid sometimes behaves differently between versions. I haven't upgraded my Orchid for a while because of that. If you are suspecting it is an issue with the node behavior I would leave a comment/issue over on Erfajo's github as the node behavior is determined by the package author there.

**Comment by judufr** [comment]
Hi,

Thank you.
But it is not the parameter name or group.
Is it possible to have a copy of your version of Orchid (impossible to find the 230.01)?

Thank you in advance.
Kind regards.

**Comment by aussieBIMguru** [comment]
Link here;
https://www.dropbox.com/sh/envy7kweptfxfxh/AAChDQz92X6fO5BU23XQ_P5ca?dl=0

I'll keep the link open until end of week, contains all the exe's and my
package folder.

I've had a lot of issues with Orchid consistency in the past. Between you
and me it's a massive pain in the butt.
I can only assume the package author makes many changes often, wastes a lot
of my time - I will avoid Orchid videos in future unfortunately.

Regards,

Gavin Crump
Content Creator
Aussie BIM Guru



*Youtube: *Link here
<https://www.youtube.com/channel/UCry22yTdpgEDdzIZig7NSMQ?>
*LinkedIn: *Link here <https://www.linkedin.com/in/gavincrump/>
*Twitter:* @AussieBIMGuru <https://twitter.com/aussiebimguru>

**Comment by judufr** [comment]
Thank you for link, times and your video's.

**Comment by judufr** [comment]
Hi,

I have find my problem and why the parameters file is broken.
It's the node witch don't like the special character (accent) for the parameter's name, that create an invisible DCS character and the datatype "FamilyType" because i didn't give the DATACATEGORY ID.
I will use your great package and this node without family type parameters (keep a little hand work).

Thank you for your help and your work.
Regards
